# Generated by Django 5.1.15 on 2026-09-20 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadeTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('open', '拉开'), ('close', '收拢')], max_length=10)),
                ('extent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('operated_at', models.DateTimeField()),
                ('operator_name', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shade_travels', to='core.zone')),
            ],
            options={
                'ordering': ['-operated_at'],
                'indexes': [models.Index(fields=['zone', 'operated_at'], name='core_shadet_zone_id_ba8113_idx')],
            },
        ),
    ]
